authors/urls.py
from django.urls import path

from authors import views

app_name = "authors"

urlpatterns = [
    path('register/', views.authors_register, name='register'),
    path('register/create/', views.register_create, name='register_create'),

    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),

    path('logout/', views.logout_view, name='logout'),
    path('logout/user/', views.logout_user, name='logout_user'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/profile', views.profile_view, name='profile'),
    path('dashboard/create', views.create_recipe, name='create_recipe'),
    path('dashboard/recipe/<int:id>/edit/',
         views.recipe_edit, name='recipe_edit'),
    path('dashboard/recipe/delete/',
         views.recipe_delete, name='recipe_delete'),



]

project/urls.py
from django.contrib import admin
from django.urls import path, include

# configuration to image

from django.conf.urls.static import static
from django.conf import settings  # importar settings da raiz do projeto

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recipes.urls")),
    path('authors/', include("authors.urls")),
]

# confirguração para images

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# confirguração para staticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipe_home, name='home'),
    path("recipes/search/", views.recipe_search, name='search'),
    path('recipes/<slug:slug>/', views.recipe_detail, name='detail'),
    path("recipes/category/<int:category_id>/",
         views.recipe_category, name='category'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
import string
import random
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.


def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class Category(models.Model):
    title = models.CharField(max_length=65)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165, )
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65, )
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65, )
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title + "-" + rand_slug())
        super(Recipe, self).save(*args, **kwargs)


# on_delete=models.SET_NULL quando deletar set este campo como nulo
# assim não gera erros

recipes/forms.py
from django import forms
from recipes.models import Recipe
from django.core.validators import ValidationError
from collections import defaultdict


def add_attr(field, attr_name, attr_new_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing_attr} {attr_new_val}'.strip()


class RecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_attr(self.fields['preparation_steps'],
                 'placeholder', 'How to prepare a  recipe')
        add_attr(self.fields['preparation_steps'],
                 'class', 'span-2')
        self._my_errors = defaultdict(list)

    title = forms.CharField(
        max_length=150,
        min_length=4,
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Recipe Title',
        }),
        label="Title",
        error_messages={
            'required': 'This field is required',
            'min_length': 'Make sure the value is at least 4 characters',
            'max_length': 'Make sure the value is a maximum of 150 characters.'
        }
    )
    description = forms.CharField(
        max_length=150,
        min_length=4,
        required=True,
        label="Description",
        widget=forms.TextInput(attrs={
            'placeholder': 'Description recipe',
        }),
        error_messages={
            'required': 'This field is required',
            'min_length': 'Make sure the value is at least 4 characters',
            'max_length': 'Make sure the value is a maximum of 150 characters.'
        }
    )

    class Meta:
        model = Recipe
        exclude = ['is_published', 'author',
                   'preparation_steps_is_html', 'slug']
        error_messages = {

            'preparation_time': {
                'required': 'This field is required'
            },
            'preparation_time_unit': {
                'required': 'This field is required'
            },
            'servings': {
                'required': 'This field is required'
            },
            'servings_unit': {
                'required': 'This field is required'
            },
            'preparation_steps': {
                'required': 'This field is required'
            },
            'category': {
                'required': 'This field is required'
            },
        }

        widgets = {
            "cover": forms.FileInput(
                attrs={
                    'class': 'span-2',
                    'accept': "image/*",
                    'onchange': 'validateSize(this)'
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ("Pessoas", 'Pessoas'),
                    ("Porções", 'Porções'),
                    ("Pedaços", 'Pedaços'),
                ),
                attrs={
                    'placeholder': 'Select servings unit'
                },

            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ("Minutos", 'Minutos'),
                    ("Horas", 'Horas'),
                ),
                attrs={
                    'placeholder': 'Recipe preparation time unit'
                }
            )
        }

        help_texts = {
            'cover': 'Maximum size file ( 2MB ).'
        }

    def clean_category(self):
        data = self.cleaned_data.get('category')

        if data is None:
            self._my_errors['category'].append('This field is required')

        return data

    def clean_preparation_time(self):
        data = self.cleaned_data.get('preparation_time')
        if data <= 0:
            self._my_errors['preparation_time'].append('Invalid number')

        return data

    def clean_servings(self):
        data = self.cleaned_data.get('servings')
        if data <= 0:

            self._my_errors['servings'].append('Invalid number')

        return data

    def clean_cover(self):
        data = self.cleaned_data.get('cover')
        if data is None:
            self._my_errors['cover'].append('This field is required')
        else:
            megabyte = 1024 * 1024
            if data.size / megabyte > 2:
                self._my_errors['cover'].append('Maximum size reached ( 2MB )')
        return data

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)

        if self._my_errors:
            raise ValidationError(self._my_errors, code='invalid')

        return super_clean

recipes/views.py
import os
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.http import Http404
from django.contrib import messages
from django.db.models import Q
from recipes.models import Recipe
from utils.pagnation import make_pagination

# Create your views here.
# teste djanggo
PER_PAGE = int(os.environ.get('PER_PAGE', 9))
QTY_LINK_PAGE = int(os.environ.get('QTY_LINK_PAGE', 4))


def recipe_home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(
        request, recipes, PER_PAGE, QTY_LINK_PAGE)

    return render(request, 'recipes/pages/recipes_home.html', {
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


def recipe_detail(request, slug):
    recipe = get_object_or_404(Recipe, slug=slug, is_published=True)

    return render(request, 'recipes/pages/recipes_detail.html', {
        'recipe': recipe,
        'is_detail_page': True

    })


def recipe_category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.filter(
        category__id=category_id, is_published=True).order_by('-id'))

    page_obj, pagination_range = make_pagination(
        request, recipes, PER_PAGE, QTY_LINK_PAGE)
    return render(request, 'recipes/pages/recipes_category.html', {
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'category_title': f'{recipes[0].category.title} - categoria'
    })


def recipe_search(request):
    search_term = request.GET.get('search', '').strip()
    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True,
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(
        request, recipes, PER_PAGE, QTY_LINK_PAGE)

    return render(request, 'recipes/pages/recipes_search.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'search': search_term,
        'additional_url_query': f'&search={search_term}'
    })

recipes/templates/recipes/partials/card_recipe.html
    <div class="card ">
        {% if recipe.cover %}
        <a class="text-decoration-none pointer"href="{{recipe.get_absolute_url}}">
            <img class="card-img-top " src="{{recipe.cover.url}}" alt="Card image cap">
        </a>
        {% endif %}
        <div class="card-body">
            <a class="text-decoration-none" href="{% url 'recipes:detail' recipe.slug %}">
                <h5 class="card-title color-title">
                    {{recipe.title}}
                </h5>
            </a>
            
          
            <span class="mr-2"> 
                {% if recipe.author is not None %}
                    <i class="fas fa-user"></i>
                    {% if recipe.author.first_name %} 
                        {{recipe.author.first_name}} {{recipe.author.last_name}}
                    {% else %}
                        {{recipe.author.username}}
                    {% endif %}
                {% else %}
                    <i class="fas fa-user"></i> Desconhecido
                {%endif%}
                    
            </span>
            <br>
            <span> 
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at|date:"SHORT_DATE_FORMAT" }} ás {{ recipe.created_at|time:"H:i" }}
            </span>
            <br>
           <span>
             <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                {{recipe.category.title}}
             </a>
           </span>
           <div class="card-content mt-1 py-0">
                <p class="py-0">
                    {{recipe.description}}
                </p>
           </div>
       
        </div>
        <div>
            <div class="d-flex justify-content-around py-2" style="background-color: #bdbdbd ">
                <div class="d-flex flex-column align-items-center">
                     <h5 class="">
                         <i class="fas fa-stopwatch"></i> Preparo
                     </h5>
                     <span class="">15 minutos</span>
                </div>
                <div class="d-flex flex-column align-items-center">
                     <h5 class="">
                         <i class="fas fa-pizza-slice"></i> Porções
                     </h5>
                    <span class="">10 pessoas</span>
                </div>
            </div>
        </div>
        {% if is_detail_page is not True %}
            <footer class="bg-dark d-flex align-center justify-content-center py-2" >
                <a class="text-white text-decoration-none" href="">
                    <i class="fas fa-eye"></i>
                    <span class="ml-2">ver mais...</span>
                </a>
            </footer>
        {% endif %}
        {% if is_detail_page is True %}
            <div class="container py-3">
                {% if recipe.preparation_steps_is_html is True %}
                    {{recipe.preparation_steps|safe}}
                {% else %}
                    {{recipe.preparation_steps|linebreaksbr}}
                {% endif %}
            </div>
        {% endif %}
</div>
      