authors/urls.py
from django.urls import path

from authors import views

app_name = "authors"

urlpatterns = [
    path('register/', views.authors_register, name='register'),
    path('register/create/', views.register_create, name='register_create'),

    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),

    path('logout/', views.logout_view, name='logout'),
    path('logout/user/', views.logout_user, name='logout_user'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/profile', views.profile_view, name='profile'),
    path('dashboard/create', views.create_recipe, name='create_recipe'),
    path('dashboard/recipe/<int:id>/edit/',
         views.recipe_edit, name='recipe_edit'),
    path('dashboard/recipe/delete/',
         views.recipe_delete, name='recipe_delete'),



]

project/urls.py
from django.contrib import admin
from django.urls import path, include

# configuration to image

from django.conf.urls.static import static
from django.conf import settings  # importar settings da raiz do projeto

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recipes.urls")),
    path('authors/', include("authors.urls")),
]

# confirguração para images

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# confirguração para staticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/forms/author_register.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import re


# adicionar atributos no campo
def add_attr(field, attr_name, attr_new_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing_attr} {attr_new_val}'.strip()


def add_placeholder(field, placeholder_val):
    add_attr(field, 'placeholder', placeholder_val)

# validção do django.


def strong_password(value):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$')
    if not regex.match(value):
        raise ValidationError(
            'Password must have at least one uppercase letter,'
            'one lowercase letter and one number.'
            'The length should be at least 8 characters', code='invalid',)


class AuthorRegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_attr(self.fields['username'], 'placeholder', 'Your username')
        add_attr(self.fields['first_name'], 'class', '')
        add_placeholder(self.fields['first_name'], 'Ex.: john')
        add_placeholder(self.fields['last_name'], 'Ex.: Doe')
        add_placeholder(self.fields['email'], 'Ex.: email@example.com')

    # sobre escrevendo formulrios
    first_name = forms.CharField(
        error_messages={'required': 'Write your first name'},
        required=True,
        label='First name',
        max_length=150
    )
    last_name = forms.CharField(
        error_messages={'required': 'Write your last name'},
        required=True,
        label='Last name',
        max_length=150
    )

    email = forms.EmailField(
        required=True,
        error_messages={'required': 'This field is required.'},
        label='E-mail',
        help_text='The e-mail must be valid'
    )

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Type your password',
            'type': 'password',
        }),
        error_messages={
            'required': 'Password must not be empty',
        },
        help_text=(
            'Password must have at least one uppercase letter,'
            'one lowercase letter and one number.'
            'The length should be at least 8 characters'
        ),
        label='Password',
        validators=[strong_password]
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeat your password',
            'type': 'password',
        }),
        error_messages={
            'required': 'Confirm Password must not be empty',
        },
        label='Confirm Password'
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password'
        ]
        labels = {
            'username': 'Username',
            'email': 'E-mail',

        }
        error_messages = {
            'username': {
                'required': 'This field is required',
            }
        }

    # validando campos clean_name = expecifico para aquele campo
    def clean_password(self):
        data = self.cleaned_data.get('password')
        text = 'Password'
        if text in data:
            raise ValidationError(
                'Do not enter the %(value)s in the password field',
                code='invalid',
                params={'value': f'{text}'}
            )

        return data

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exits = User.objects.filter(email=email).exists()

        if exits:
            raise ValidationError(
                'The email: %(email)s is already in use',
                code='invalid',
                params={'email': email})
        return email

    # validação em geral metodo super().
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            password_confirmation_error = ValidationError(
                'Password and password2 must be equal',
                code='invalid'
            )
            raise ValidationError({
                # 'password': 'Password and password2 must be equal',
                'password': password_confirmation_error,
                'password2': [
                    password_confirmation_error,
                ],

            }, code='invalid',)


class UpdateAuthorForm(forms.ModelForm):
    # sobre escrevendo formulrios
    first_name = forms.CharField(
        error_messages={'required': 'Write your first name'},
        required=True,
        label='First name',
        max_length=150,
        widget=forms.TextInput(attrs={
            'placeholder': "Ex.: john"
        })
    )
    last_name = forms.CharField(
        error_messages={'required': 'Write your last name'},
        required=True,
        label='Last name',
        max_length=150,
        widget=forms.TextInput(attrs={
            'placeholder': "Ex.: Doe"
        })
    )

    email = forms.EmailField(
        required=True,
        error_messages={'required': 'This field is required.'},
        label='E-mail',
        help_text='The e-mail must be valid',
        widget=forms.TextInput(attrs={
            'placeholder': "Ex.: email@example.com"
        })
    )

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',

        ]
        labels = {
            'username': 'Username',
            'email': 'E-mail',
        }

        widgets = {
            'username': forms.TextInput(attrs={
                'placeholder': 'Type your username',

            }),
        }

    def clean_email(self):
        current_email = self.instance.email
        new_email = self.cleaned_data.get('email', '')
        if current_email != new_email:
            exits = User.objects.filter(email=new_email).exists()
            if exits:
                raise ValidationError(
                    'The email: %(email)s is already in use',
                    code='invalid',
                    params={'email': new_email})
        return new_email

authors/forms/login.py
from django import forms

# fromulario nao atrelado a um model


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label="Username", widget=forms.TextInput(attrs={
        'placeholder': 'Type your username'
    }))
    password = forms.CharField(required=True, label="Password", widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'type': 'password'
    }))

authors/views.py
from django.shortcuts import render, redirect, get_object_or_404
from authors.forms import AuthorRegisterForm, LoginForm, UpdateAuthorForm
from recipes.forms import RecipeForm
from recipes.models import Recipe
from django.http import Http404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from utils.pagnation import make_pagination
from django.contrib.auth.models import User
import os
PER_PAGE = int(os.environ.get('PER_PAGE', 9))
QTY_LINK_PAGE = int(os.environ.get('QTY_LINK_PAGE', 4))

# Create your views here.


def authors_register(request):
    author_register_form_data = request.session.get(
        'author_register_form_data', None)
    form = AuthorRegisterForm(author_register_form_data)
    return render(request, 'authors/pages/authors_register.html', {
        'form': form,
        'form_action': reverse('authors:register_create'),
        'view_author_register': 'active'
    })


def register_create(request):
    if not request.POST:
        raise Http404()
    POST = request.POST
    request.session['author_register_form_data'] = POST
    form = AuthorRegisterForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        messages.success(request, 'Your user is create, please log in.')

        del(request.session['author_register_form_data'])
        return redirect('authors:login')

    return redirect('authors:register')


def login_view(request):
    form = LoginForm()
    return render(request, 'authors/pages/login.html', {
        'form': form,
        'form_action': reverse('authors:login_create'),
        'view_login': 'active',
    })


def login_create(request):
    if not request.POST:
        raise Http404()
    form = LoginForm(request.POST)
    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )
        if authenticated_user is not None:
            messages.success(request, 'Your are logged in.')
            login(request, authenticated_user)
            return redirect('authors:profile')
        else:
            messages.error(request, 'Invalid credentials.')

    else:
        messages.error(request, 'Error to validate form data.')

    return redirect('authors:login')


@login_required(login_url='authors:login', redirect_field_name='next')
def profile_view(request):
    user = User.objects.get(username=request.user.username)
    form = UpdateAuthorForm(
        request.POST or None,
        instance=user
    )

    if form.is_valid():
        form.save()
        messages.success(request, 'Edit with success.')
        return redirect('authors:profile')

    return render(request, 'authors/pages/profile.html', context={
        'form': form,
    })


@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):

    return render(request, 'authors/pages/logout.html',)


@login_required(login_url='authors:login', redirect_field_name='next')
def logout_user(request):
    if not request.POST:
        return redirect('authors:login')

    if request.POST.get('username') != request.user.username:
        return redirect('authors:login')

    logout(request)
    return redirect('authors:login')


@login_required(login_url='authors:login', redirect_field_name='next')
def create_recipe(request):
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
    )

    if form.is_valid():
        recipe = form.save(commit=False)
        recipe.author = request.user
        recipe.preparation_steps_is_html = False
        recipe.is_published = False
        recipe.save()
        messages.success(request, 'Recipe create success.')
        return redirect('authors:create_recipe')

    return render(request, 'authors/pages/create_recipe.html', {'form': form})


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
    # fazer paginacao dps
    recipes = Recipe.objects.filter(
        author__username=request.user.username, is_published=False).order_by('-id')

    page_obj, pagination_range = make_pagination(
        request, recipes, PER_PAGE, QTY_LINK_PAGE)

    return render(request, 'authors/pages/dashboard.html', {
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


@login_required(login_url='authors:login', redirect_field_name='next')
def recipe_delete(request):
    if not request.POST:
        return redirect('authors:dashboard')

    id = request.POST.get('id')
    recipe = get_object_or_404(
        Recipe, pk=id, is_published=False, author=request.user)

    recipe.delete()
    messages.success(request, 'Delete with success.')
    return redirect('authors:dashboard')


@login_required(login_url='authors:login', redirect_field_name='next')
def recipe_edit(request, id):
    recipe = get_object_or_404(
        Recipe, pk=id, is_published=False, author=request.user)
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe
    )
    if form.is_valid():
        recipe = form.save(commit=False)
        recipe.author = request.user
        recipe.preparation_steps_is_html = False
        recipe.is_published = False
        recipe.save()
        messages.success(request, 'Edit with success.')
        return redirect(reverse('authors:recipe_edit', args=(id,)))

    return render(request, 'authors/pages/create_recipe.html', context={
        'form': form,

    })

authors/templates/authors/pages/authors_register.html
{% extends 'global/base.html' %}

{% block title %}
    Authors
{% endblock title %}

{% block content %}
{% include 'global/partials/messages.html' %}
<h2 class="text-center mt-4">Register</h2>
{% include 'global/partials/form.html' %}

{% endblock content %}

authors/templates/authors/pages/create_recipe.html
{% extends 'global/base.html'%}
{% block title %}
    {{title}} | User
{% endblock %}

{% block content %}
    <h2 class="text-center my-4">Criar Receitas</h2>
    {% include 'global/partials/messages.html' %}

    <div class="text-left">
            {% include 'global/partials/form.html' %}
    </div>
        
 
{% endblock content %}

authors/templates/authors/pages/dashboard.html
{% extends 'global/base.html'%}
{% load static %}
{% block title %}
Dashboard
{% endblock %}

{% block content %}

        <h2 class="text-center my-4" >Dashboard ({{user}})</h2>

        {% include 'global/partials/messages.html' %}
    
        <h3 class="text-left my-4">Your recipes</h3>
        <div class="table-responsive">
            <table class="table table-striped table-dark">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Data de criação</th>
                <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for recipe in recipes %}
                <tr>
                    <th scope="row">{{recipe.id}}</th>
                    <td>{{recipe.title}}</td>
                    <td>  {{ recipe.created_at|date:"SHORT_DATE_FORMAT" }} ás {{ recipe.created_at|time:"H:i" }}</td>
                    <td> 
                        <div class="d-flex flex-nowrap">
                            <a href="{% url 'authors:recipe_edit' recipe.id %}" type="button" class="btn btn-success mr-2" >Editar</a> 
                            <form id="form-delete" class="form-delete ml-2 " action="{% url 'authors:recipe_delete'%}" method="post">
                                {% csrf_token %}
                                <input required type="hidden" name="id" value="{{ recipe.id}}">
                                <button type="submit" class="btn btn-danger">Deletar</button> 
                            </form>
                            
                        </div>
                    </td>
                </tr>
                {% endfor %}
              
            </tbody>
            </table>
        </div>
{% endblock content %}

{% block script_extras %}
<script src="{% static 'global/js/recipe_delete.js' %}"></script>
{% endblock script_extras %}

authors/templates/authors/pages/login.html
{% extends 'global/base.html' %}
{% block title %}
Login | User
{%endblock %}

{% block content %}
   {% include 'global/partials/messages.html' %}
    <h2 class="text-center my-4">Login</h2>
   
    {% if not request.user.is_authenticated %}
        {% include 'global/partials/form.html' %}
    {% else %}
    <div style="margin: 0 auto"  class="search alert alert-success">
        you are logged in.</div>
    {% endif %}
{% endblock content %}

authors/templates/authors/pages/logout.html
{% extends 'global/base.html' %}
{% block title %}
Logout | User
{%endblock %}

{% block content %}
        <h2 class="text-center my-4"></h2>
        {% if request.user.is_authenticated %}
            <br>
            <div class="container">
                <form action="{% url 'authors:logout_user' %}"  method="POST">
                    {% csrf_token %}
                    <p class="text-center">Are you sure you want to quit ? </p>
                    <br>
                    <br>
                    <input type="hidden" name="username" value="{{ request.user.username }}">
                    <div class="form-content text-center">
                        <div class="form-group">
                            <button class="btn"type="submit">Logout</button>
                        </div>
                    </div>
                </form>
            </div>
        {% endif %}

{% endblock content %}

authors/templates/authors/pages/profile.html
{% extends 'global/base.html'%}
{% block title %} | User
{% endblock %}

{% block content %}
    <h2 class="text-center mt-3 mb-5">Profile</h2>
     
    {% include 'global/partials/messages.html' %}      
    <div class="text-left">
        {% include 'global/partials/form.html' %}
    </div>
  
 
{% endblock content %}